version: '3.8'

services:
  detector:
    build: .
    volumes:
      - ./config:/app/config
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - DETECTOR_CONFIDENCE=0.5
      - DEBUG_MODE=false
    devices:
      - /dev/video0:/dev/video0  # For camera access
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=detector
      - POSTGRES_PASSWORD=detector
      - POSTGRES_DB=license_plates
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  monitoring:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

volumes:
  postgres_data:
  grafana_data:
  prometheus_data: